import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { normalize as normalizeDoc, MARK_KINDS, type Block, type BlockAttrs, type MarkRange, type ScreenplayDocument } from "@fylym/screenplay-core";
import { arbitraryDocument, arbitraryDualDialogueGroup } from "@fylym/screenplay-core/testing";
import { toBlocks, toPmDoc } from "./converters.js";

function sortedMarks(marks: MarkRange[]): MarkRange[] {
  return [...marks].sort((a, b) => a.kind.localeCompare(b.kind) || a.start - b.start || a.end - b.end);
}

/**
 * Structural comparison including ids — unlike a round-trip through
 * Fountain/FDX (plain text, no id concept), toPmDoc stores Block.id as a
 * node attr, so toBlocks(toPmDoc(blocks)) is expected to preserve ids
 * exactly, not just structure. Mark order within a block is still
 * normalized before comparing: ProseMirror's Mark set is canonically
 * ordered by schema rank, not by the order marks were constructed in, so
 * that's not a meaningful difference to assert on (same as the FDX/PDF
 * mark-order handling elsewhere in this codebase).
 */
function canonical(blocks: Block[]): unknown {
  return blocks.map((b) => ({ ...b, marks: sortedMarks(b.marks) }));
}

/**
 * screenplay-core's arbitraryBlock/arbitraryDocument generate *syntactically*
 * valid blocks but don't guarantee every structural invariant (e.g. they can
 * produce two overlapping marks of the same kind) — normalize() is what
 * repairs that, same as the Fountain/FDX round-trip tests already do before
 * comparing. Without it, toPmDoc's mark Set correctly collapses duplicate/
 * overlapping same-kind marks into one, and the naive pre-normalize input
 * looks like a "lost mark" that was never actually there once repaired.
 */
function normalizedBlocks(doc: ScreenplayDocument): Block[] {
  return normalizeDoc(doc).blocks;
}

describe("toBlocks(toPmDoc(blocks)) round-trip (property)", () => {
  it("holds for arbitrary valid documents generated by screenplay-core's own testing helpers", () => {
    fc.assert(
      fc.property(arbitraryDocument, (doc) => {
        const input = normalizedBlocks(doc);
        const roundTripped = toBlocks(toPmDoc(input));
        expect(canonical(roundTripped)).toEqual(canonical(input));
      }),
      { numRuns: 2000 },
    );
  });

  it("holds for dual-dialogue groups specifically", () => {
    fc.assert(
      fc.property(arbitraryDualDialogueGroup, (blocks) => {
        const input = normalizedBlocks({ blocks });
        const roundTripped = toBlocks(toPmDoc(input));
        expect(canonical(roundTripped)).toEqual(canonical(input));
      }),
      { numRuns: 500 },
    );
  });

  it("preserves overlapping marks of different kinds (bold+italic simultaneously)", () => {
    const blocks: Block[] = [
      {
        id: "b1",
        type: "action",
        text: "hello world",
        marks: [
          { kind: "bold", start: 0, end: 11 },
          { kind: "italic", start: 6, end: 11 },
        ],
        attrs: {},
      },
    ];
    const roundTripped = toBlocks(toPmDoc(blocks));
    expect(canonical(roundTripped)).toEqual(canonical(blocks));
  });

  it("preserves a revision mark's revisionColor", () => {
    const blocks: Block[] = [
      {
        id: "b1",
        type: "action",
        text: "hello",
        marks: [{ kind: "revision", start: 0, end: 5, revisionColor: "Blue" }],
        attrs: {},
      },
    ];
    const roundTripped = toBlocks(toPmDoc(blocks));
    expect(roundTripped[0]?.marks).toEqual([{ kind: "revision", start: 0, end: 5, revisionColor: "Blue" }]);
  });

  it("preserves every BlockAttrs field, including passthrough", () => {
    const attrs: BlockAttrs = {
      sceneNumber: "12A",
      revision: "Blue",
      locked: true,
      elementNumber: "E7",
      passthrough: { fdxParagraph: { "@_Custom": "1" } },
    };
    const blocks: Block[] = [{ id: "b1", type: "scene_heading", text: "INT. HOUSE - DAY", marks: [], attrs }];
    const roundTripped = toBlocks(toPmDoc(blocks));
    expect(roundTripped[0]?.attrs).toEqual(attrs);
  });

  it("omits locked from output attrs when false or absent (semantically equivalent optional-boolean convention)", () => {
    const blocks: Block[] = [
      { id: "b1", type: "action", text: "a", marks: [], attrs: {} },
      { id: "b2", type: "action", text: "b", marks: [], attrs: { locked: false } },
    ];
    const roundTripped = toBlocks(toPmDoc(blocks));
    expect(roundTripped[0]?.attrs.locked).toBeUndefined();
    expect(roundTripped[1]?.attrs.locked).toBeUndefined();
  });

  it("round-trips an empty document", () => {
    expect(toBlocks(toPmDoc([]))).toEqual([]);
  });

  it("round-trips a block with empty text and no marks", () => {
    const blocks: Block[] = [{ id: "b1", type: "page_break", text: "", marks: [], attrs: {} }];
    expect(toBlocks(toPmDoc(blocks))).toEqual(blocks);
  });
});

describe("MARK_KINDS coverage sanity", () => {
  it("schema round-trips every mark kind at least once", () => {
    const blocks: Block[] = [
      {
        id: "b1",
        type: "action",
        text: "abcde",
        marks: MARK_KINDS.map((kind, i): MarkRange => ({ kind, start: i, end: i + 1 })),
        attrs: {},
      },
    ];
    const roundTripped = toBlocks(toPmDoc(blocks));
    const kindsSeen = new Set(roundTripped[0]?.marks.map((m) => m.kind));
    for (const kind of MARK_KINDS) expect(kindsSeen.has(kind)).toBe(true);
  });
});
